<nav class="navbar navbar-inverse navbar-static-top" rule="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand"><img src=" <?php echo $this->basePath('img/zf2-logo.png') ?> " alt="ZendFrameWork"/>
			&nbsp;<?php echo $this->translate('QuizComputer') ?></a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href=" <?php echo $this->url('home') ?> "><?php echo $this->translate('Home') ?></a></li>
			</ul>
		</div>
	</div>
</nav>

<h1>Examinator Login pagina</h1>
	<?php // view helper
	    if ($user = $this->identity()) {
	        echo 'Logged in as ' . $this->escapeHtml($user->userName);
	    }
	?> 
	<a href="<?php echo $this->url('auth/default', array('controller' => 'examinator', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a>

	<?php var_dump($results); ?>
	</tbody>
</table>