<nav class="navbar navbar-inverse navbar-static-top" rule="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand"><img src=" <?php echo $this->basePath('img/zf2-logo.png') ?> " alt="ZendFrameWork"/>
			&nbsp;<?php echo $this->translate('QuizComputer') ?></a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href=" <?php echo $this->url('home') ?> "><?php echo $this->translate('Home') ?></a></li>
			</ul>
		</div>
	</div>
</nav>

<h1>Beheerder startpagina</h1>
<?php // view helper
    if ($user = $this->identity()) {
        echo 'Logged in as ' . $this->escapeHtml($user->userName);
    }
?> 
<br>
<a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'create')); ?>">Create User</a>
||
<a href="<?php echo $this->url('auth/default', array('controller' => 'examinator', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>Username</th>
			<th>Role</th>
			<th></th>
			<th></th>
		</tr>
	</thead>
	<tbody>
<?php
	foreach ($rowset as $row) {
?>
		<tr>
			<td><?php  echo $row['userName']; ?></td>
			<td><?php  echo ($row['UserGroup_idUserGroup']==1 ?  "Admin" :  "Examinator"); ?></td>
			<td><a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'update', 'id' => $row['idUsers'])); ?>">Edit</a></td>
			<td><a href="<?php echo $this->url('auth/default', array('controller' => 'admin', 'action' => 'delete', 'id' => $row['idUsers'])); ?>" 
					onclick="return confirm('Do you really want to delete the record;')">Delete</a></td>
		</tr>
<?php
	}
?>
	</tbody>
</table>



